//11. Explicar la diferencia entre un union y un struct.

//STRUCT ES UN CONSTRUCTOR DE DATOS EN EL QUE CADA ELEMENTO OCUPA SU ESPACIO EN MEMORIA DEPENDIENDO SU TIPO DE DATO, TODOS LOS ELEMENTOS DE LA STRUCT SON ACCESIBLES EN CUALQUIER MOMENTO.

//LA UNION ES UN CONSTRUCTOR EN EL QUE TODOS LOS ELEMENTOS OCUPAN EL MISMO ESPACIO EN MEMORIA, EL ESPACIO DEL TIPO DE DATO MAS GRANDE, Y SOLO UN ELEMENTO DE LA UNION ES ACCESIBLE EN UN MOMENTO
//DADO

//STRUCT ES MEJOR SI TENGO QUE MANEJAR TIPOS DE DATOS DIFERENTES QUE ESTEN RELACIONADOS, UNION ES MEJOR SI SOLO TENGO QUE TRABAJAR MOMENTANEAMENTE CON TIPOS DE DATOS Y DESEO MANEJAR LA MEMORIA DE MANERA
//MAS EFICIENTE

